#!/usr/bin/env php

<?php

require_once __DIR__.'/../vendor/autoload.php';

use Play\Command\GreetCommand;
use Play\Command\GreetToonCommand;
use Symfony\Component\Console\Application;

$application = new Application();
$application->add(new GreetCommand);
$application->add(new GreetToonCommand);
$application->run();
